// WHO SMART Guidelines knowledge graph -- L1 ONTOLOGY (type graph).
// Generated by tools/build-exports.mjs. Do not edit; edit the ontology JSON.
//
// These are CLASSES and LICENSED EDGES, not DAK instance data. Loading this gives you the
// schema to explore; a DAK's own graph is generated by that DAK's IG build. See docs/STORAGE.md.
//
// Every statement is MERGE, so re-running is safe.
//
// RUN THIS AGAINST A USER DATABASE, NOT `system`. The CREATE CONSTRAINT below is rejected
// with "can only be executed in a user database" if `system` is selected, which is where
// Neo4j Browser can land you after connecting. Switch first:
//
//     :use neo4j                                    (Browser, or your database's name)
//     cypher-shell -d neo4j -f <this file>           (shell)

CREATE CONSTRAINT kgclass_id IF NOT EXISTS
FOR (c:KGClass) REQUIRE c.id IS UNIQUE;

MERGE (:KGClass:Source {id:'publication', name:'Publication', kind:'Source', layer:'l1', iri:'http://smart.who.int/kg/publication'});
MERGE (:KGClass:Source {id:'publication-section', name:'Publication section', kind:'Source', layer:'l1', iri:'http://smart.who.int/kg/publication-section'});
MERGE (:KGClass:Source {id:'publication-element', name:'Publication element', kind:'Source', layer:'l1', iri:'http://smart.who.int/kg/publication-element'});
MERGE (:KGClass:Concept {id:'recommendation', name:'Recommendation', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/recommendation'});
MERGE (:KGClass:Concept {id:'remark', name:'Remark', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/remark'});
MERGE (:KGClass:Concept {id:'key-question', name:'Key question', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/key-question'});
MERGE (:KGClass:Concept {id:'outcome', name:'Outcome', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/outcome'});
MERGE (:KGClass:Concept {id:'evidence', name:'Evidence', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/evidence'});
MERGE (:KGClass:Concept {id:'health-intervention', name:'Health intervention', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/health-intervention'});
MERGE (:KGClass:Concept {id:'indicator', name:'Indicator', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/indicator'});
MERGE (:KGClass:Reference {id:'citation', name:'Citation', kind:'Reference', layer:'l1', iri:'http://smart.who.int/kg/citation'});
MERGE (:KGClass:Reference {id:'reference-entry', name:'Reference entry', kind:'Reference', layer:'l1', iri:'http://smart.who.int/kg/reference-entry'});
MERGE (:KGClass:Reference {id:'terminology-code', name:'Terminology code', kind:'Reference', layer:'l1', iri:'http://smart.who.int/kg/terminology-code'});

MATCH (s:KGClass {id:'publication'}), (t:KGClass {id:'publication-section'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'publication-section'}), (t:KGClass {id:'publication-section'}) MERGE (s)-[:CONTAINS {predicate:'contains', qualifier:'subsection'}]->(t);
MATCH (s:KGClass {id:'publication-section'}), (t:KGClass {id:'publication-element'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'publication'}), (t:KGClass {id:'publication-element'}) MERGE (s)-[:CONTAINS {predicate:'contains', qualifier:'unsectioned'}]->(t);
MATCH (s:KGClass {id:'publication-element'}), (t:KGClass {id:'publication-element'}) MERGE (s)-[:CONTAINS {predicate:'contains', qualifier:'part'}]->(t);
MATCH (s:KGClass {id:'publication'}), (t:KGClass {id:'publication'}) MERGE (s)-[:HASSUPPLEMENT {predicate:'hasSupplement'}]->(t);
MATCH (s:KGClass {id:'publication'}), (t:KGClass {id:'publication'}) MERGE (s)-[:SUPERSEDES {predicate:'supersedes'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:SUPERSEDES {predicate:'supersedes'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:REFINES {predicate:'refines'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:PARTOF {predicate:'partOf'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'publication'}) MERGE (s)-[:DEFINEDIN {predicate:'definedIn'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'publication'}) MERGE (s)-[:DEFINEDIN {predicate:'definedIn'}]->(t);
MATCH (s:KGClass {id:'health-intervention'}), (t:KGClass {id:'publication'}) MERGE (s)-[:DEFINEDIN {predicate:'definedIn'}]->(t);
MATCH (s:KGClass {id:'key-question'}), (t:KGClass {id:'publication'}) MERGE (s)-[:DEFINEDIN {predicate:'definedIn'}]->(t);
MATCH (s:KGClass {id:'evidence'}), (t:KGClass {id:'publication'}) MERGE (s)-[:DEFINEDIN {predicate:'definedIn'}]->(t);
MATCH (s:KGClass {id:'outcome'}), (t:KGClass {id:'publication'}) MERGE (s)-[:DEFINEDIN {predicate:'definedIn'}]->(t);
MATCH (s:KGClass {id:'remark'}), (t:KGClass {id:'publication'}) MERGE (s)-[:DEFINEDIN {predicate:'definedIn'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'publication-section'}) MERGE (s)-[:PRESENTEDIN {predicate:'presentedIn'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'publication-element'}) MERGE (s)-[:PRESENTEDIN {predicate:'presentedIn'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'publication-section'}) MERGE (s)-[:PRESENTEDIN {predicate:'presentedIn'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'publication-element'}) MERGE (s)-[:PRESENTEDIN {predicate:'presentedIn'}]->(t);
MATCH (s:KGClass {id:'health-intervention'}), (t:KGClass {id:'publication-section'}) MERGE (s)-[:PRESENTEDIN {predicate:'presentedIn'}]->(t);
MATCH (s:KGClass {id:'health-intervention'}), (t:KGClass {id:'publication-element'}) MERGE (s)-[:PRESENTEDIN {predicate:'presentedIn'}]->(t);
MATCH (s:KGClass {id:'key-question'}), (t:KGClass {id:'publication-section'}) MERGE (s)-[:PRESENTEDIN {predicate:'presentedIn'}]->(t);
MATCH (s:KGClass {id:'key-question'}), (t:KGClass {id:'publication-element'}) MERGE (s)-[:PRESENTEDIN {predicate:'presentedIn'}]->(t);
MATCH (s:KGClass {id:'evidence'}), (t:KGClass {id:'publication-section'}) MERGE (s)-[:PRESENTEDIN {predicate:'presentedIn'}]->(t);
MATCH (s:KGClass {id:'evidence'}), (t:KGClass {id:'publication-element'}) MERGE (s)-[:PRESENTEDIN {predicate:'presentedIn'}]->(t);
MATCH (s:KGClass {id:'outcome'}), (t:KGClass {id:'publication-section'}) MERGE (s)-[:PRESENTEDIN {predicate:'presentedIn'}]->(t);
MATCH (s:KGClass {id:'outcome'}), (t:KGClass {id:'publication-element'}) MERGE (s)-[:PRESENTEDIN {predicate:'presentedIn'}]->(t);
MATCH (s:KGClass {id:'remark'}), (t:KGClass {id:'publication-section'}) MERGE (s)-[:PRESENTEDIN {predicate:'presentedIn'}]->(t);
MATCH (s:KGClass {id:'remark'}), (t:KGClass {id:'publication-element'}) MERGE (s)-[:PRESENTEDIN {predicate:'presentedIn'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'key-question'}) MERGE (s)-[:ANSWERS {predicate:'answers'}]->(t);
MATCH (s:KGClass {id:'evidence'}), (t:KGClass {id:'key-question'}) MERGE (s)-[:ADDRESSES {predicate:'addresses'}]->(t);
MATCH (s:KGClass {id:'key-question'}), (t:KGClass {id:'outcome'}) MERGE (s)-[:HASOUTCOME {predicate:'hasOutcome'}]->(t);
MATCH (s:KGClass {id:'evidence'}), (t:KGClass {id:'outcome'}) MERGE (s)-[:FOROUTCOME {predicate:'forOutcome'}]->(t);
MATCH (s:KGClass {id:'key-question'}), (t:KGClass {id:'health-intervention'}) MERGE (s)-[:ABOUTINTERVENTION {predicate:'aboutIntervention'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'evidence'}) MERGE (s)-[:SUPPORTEDBY {predicate:'supportedBy'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'remark'}) MERGE (s)-[:HASREMARK {predicate:'hasRemark'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'health-intervention'}) MERGE (s)-[:RECOMMENDS {predicate:'recommends'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'health-intervention'}) MERGE (s)-[:MEASURES {predicate:'measures'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:MEASURES {predicate:'measures'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:JUSTIFIEDBY {predicate:'justifiedBy'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences', qualifier:'intervention'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences', qualifier:'population'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences', qualifier:'setting'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences', qualifier:'provider'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences', qualifier:'timing'}]->(t);
MATCH (s:KGClass {id:'key-question'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'health-intervention'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'outcome'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'health-intervention'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CLASSIFIEDAS {predicate:'classifiedAs', qualifier:'UHC'}]->(t);
MATCH (s:KGClass {id:'health-intervention'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CLASSIFIEDAS {predicate:'classifiedAs', qualifier:'ICHI'}]->(t);
MATCH (s:KGClass {id:'health-intervention'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CLASSIFIEDAS {predicate:'classifiedAs', qualifier:'CDHI'}]->(t);
MATCH (s:KGClass {id:'citation'}), (t:KGClass {id:'reference-entry'}) MERGE (s)-[:NUMBEREDAS {predicate:'numberedAs'}]->(t);
MATCH (s:KGClass {id:'citation'}), (t:KGClass {id:'publication'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'citation'}), (t:KGClass {id:'publication-section'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'citation'}), (t:KGClass {id:'publication-element'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'citation'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'citation'}), (t:KGClass {id:'indicator'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'citation'}), (t:KGClass {id:'health-intervention'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'reference-entry'}), (t:KGClass {id:'publication'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'reference-entry'}), (t:KGClass {id:'publication-section'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'reference-entry'}), (t:KGClass {id:'publication-element'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'reference-entry'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'reference-entry'}), (t:KGClass {id:'indicator'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'reference-entry'}), (t:KGClass {id:'health-intervention'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
