// WHO SMART Guidelines knowledge graph -- L1 ONTOLOGY (type graph).
// Generated by tools/build-exports.mjs. Do not edit; edit the ontology JSON.
//
// These are CLASSES and LICENSED EDGES, not DAK instance data. Loading this gives you the
// schema to explore; a DAK's own graph is generated by that DAK's IG build. See docs/STORAGE.md.
//
// Every statement is MERGE, so re-running is safe.

CREATE CONSTRAINT kgclass_id IF NOT EXISTS
FOR (c:KGClass) REQUIRE c.id IS UNIQUE;

MERGE (:KGClass:Source {id:'publication', name:'Publication', kind:'Source', iri:'http://smart.who.int/kg/publication'});
MERGE (:KGClass:Source {id:'publication-section', name:'Publication section', kind:'Source', iri:'http://smart.who.int/kg/publication-section'});
MERGE (:KGClass:Concept {id:'recommendation', name:'Recommendation', kind:'Concept', iri:'http://smart.who.int/kg/recommendation'});
MERGE (:KGClass:Concept {id:'remark', name:'Remark', kind:'Concept', iri:'http://smart.who.int/kg/remark'});
MERGE (:KGClass:Concept {id:'evidence', name:'Evidence', kind:'Concept', iri:'http://smart.who.int/kg/evidence'});
MERGE (:KGClass:Concept {id:'population', name:'Population', kind:'Concept', iri:'http://smart.who.int/kg/population'});
MERGE (:KGClass:Concept {id:'intervention', name:'Intervention', kind:'Concept', iri:'http://smart.who.int/kg/intervention'});
MERGE (:KGClass:Concept {id:'comparator', name:'Comparator', kind:'Concept', iri:'http://smart.who.int/kg/comparator'});
MERGE (:KGClass:Concept {id:'outcome', name:'Outcome', kind:'Concept', iri:'http://smart.who.int/kg/outcome'});
MERGE (:KGClass:Concept {id:'health-intervention', name:'Health intervention', kind:'Concept', iri:'http://smart.who.int/kg/health-intervention'});
MERGE (:KGClass:Concept {id:'schedule', name:'Schedule', kind:'Concept', iri:'http://smart.who.int/kg/schedule'});
MERGE (:KGClass:Concept {id:'schedule-entry', name:'Schedule entry', kind:'Concept', iri:'http://smart.who.int/kg/schedule-entry'});
MERGE (:KGClass:Concept {id:'indicator', name:'Indicator', kind:'Concept', iri:'http://smart.who.int/kg/indicator'});
MERGE (:KGClass:Reference {id:'terminology-code', name:'Terminology code', kind:'Reference', iri:'http://smart.who.int/kg/terminology-code'});
MERGE (:KGClass:Reference {id:'citation', name:'Citation', kind:'Reference', iri:'http://smart.who.int/kg/citation'});
MERGE (:KGClass:Reference {id:'external-artifact', name:'External artefact', kind:'Reference', iri:'http://smart.who.int/kg/external-artifact'});

MATCH (s:KGClass {id:'publication'}), (t:KGClass {id:'publication-section'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'publication-section'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'publication'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:CONTAINS {predicate:'contains', qualifier:'unsectioned'}]->(t);
MATCH (s:KGClass {id:'publication'}), (t:KGClass {id:'publication'}) MERGE (s)-[:SUPERSEDES {predicate:'supersedes'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:REFINES {predicate:'refines'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'population'}) MERGE (s)-[:HASPOPULATION {predicate:'hasPopulation'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'intervention'}) MERGE (s)-[:HASINTERVENTION {predicate:'hasIntervention'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'comparator'}) MERGE (s)-[:HASCOMPARATOR {predicate:'hasComparator'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'outcome'}) MERGE (s)-[:HASOUTCOME {predicate:'hasOutcome'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'evidence'}) MERGE (s)-[:SUPPORTEDBY {predicate:'supportedBy'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'remark'}) MERGE (s)-[:HASREMARK {predicate:'hasRemark'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'health-intervention'}) MERGE (s)-[:RECOMMENDS {predicate:'recommends'}]->(t);
MATCH (s:KGClass {id:'schedule'}), (t:KGClass {id:'publication'}) MERGE (s)-[:DEFINEDIN {predicate:'definedIn'}]->(t);
MATCH (s:KGClass {id:'schedule'}), (t:KGClass {id:'schedule-entry'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'schedule-entry'}), (t:KGClass {id:'health-intervention'}) MERGE (s)-[:SCHEDULES {predicate:'schedules'}]->(t);
MATCH (s:KGClass {id:'schedule-entry'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:DERIVEDFROM {predicate:'derivedFrom'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'publication'}) MERGE (s)-[:DEFINEDIN {predicate:'definedIn'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'health-intervention'}) MERGE (s)-[:MEASURES {predicate:'measures'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:DERIVEDFROM {predicate:'derivedFrom'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'population'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'intervention'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'outcome'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'schedule-entry'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'health-intervention'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'health-intervention'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CLASSIFIEDAS {predicate:'classifiedAs', qualifier:'CDHI'}]->(t);
MATCH (s:KGClass {id:'citation'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:APPEARSIN {predicate:'appearsIn'}]->(t);
MATCH (s:KGClass {id:'citation'}), (t:KGClass {id:'publication'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'citation'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'citation'}), (t:KGClass {id:'schedule'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'schedule-entry'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'health-intervention'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
