// WHO SMART Guidelines knowledge graph -- L2 ONTOLOGY (type graph).
// Generated by tools/build-exports.mjs. Do not edit; edit the ontology JSON.
//
// These are CLASSES and LICENSED EDGES, not DAK instance data. Loading this gives you the
// schema to explore; a DAK's own graph is generated by that DAK's IG build. See docs/STORAGE.md.
//
// Every statement is MERGE, so re-running is safe.
//
// REQUIRES l1.cypher TO BE LOADED FIRST.
// This layer licenses edges onto imported classes (citation, external-artifact, terminology-code). The MATCH
// statements below find nothing if those classes are absent, and Cypher does not treat
// that as an error -- the edges would simply be missing. Verify with the query at the
// end of this file.

CREATE CONSTRAINT kgclass_id IF NOT EXISTS
FOR (c:KGClass) REQUIRE c.id IS UNIQUE;

MERGE (:KGClass:Artefact {id:'business-process', name:'Business Process', kind:'Artefact', iri:'http://smart.who.int/kg/business-process'});
MERGE (:KGClass:Structure {id:'process-participant', name:'Process Participant', kind:'Structure', iri:'http://smart.who.int/kg/process-participant'});
MERGE (:KGClass:Structure {id:'process-task', name:'Process Task', kind:'Structure', iri:'http://smart.who.int/kg/process-task'});
MERGE (:KGClass:Structure {id:'process-gateway', name:'Process Gateway', kind:'Structure', iri:'http://smart.who.int/kg/process-gateway'});
MERGE (:KGClass:Structure {id:'process-event', name:'Process Event', kind:'Structure', iri:'http://smart.who.int/kg/process-event'});
MERGE (:KGClass:Artefact {id:'decision-table', name:'Decision Table', kind:'Artefact', iri:'http://smart.who.int/kg/decision-table'});
MERGE (:KGClass:Structure {id:'input-clause', name:'Input Clause', kind:'Structure', iri:'http://smart.who.int/kg/input-clause'});
MERGE (:KGClass:Structure {id:'output-clause', name:'Output Clause', kind:'Structure', iri:'http://smart.who.int/kg/output-clause'});
MERGE (:KGClass:Structure {id:'decision-rule', name:'Decision Rule', kind:'Structure', iri:'http://smart.who.int/kg/decision-rule'});
MERGE (:KGClass:Definition {id:'persona', name:'Persona', kind:'Definition', iri:'http://smart.who.int/kg/persona'});
MERGE (:KGClass:Definition {id:'data-element', name:'Data Element', kind:'Definition', iri:'http://smart.who.int/kg/data-element'});

MATCH (s:KGClass {id:'business-process'}), (t:KGClass {id:'process-participant'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'business-process'}), (t:KGClass {id:'process-task'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'business-process'}), (t:KGClass {id:'process-gateway'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'business-process'}), (t:KGClass {id:'process-event'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'process-participant'}), (t:KGClass {id:'process-task'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'process-participant'}), (t:KGClass {id:'process-gateway'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'process-participant'}), (t:KGClass {id:'process-event'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'process-task'}), (t:KGClass {id:'process-task'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'decision-table'}), (t:KGClass {id:'input-clause'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'decision-table'}), (t:KGClass {id:'output-clause'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'decision-table'}), (t:KGClass {id:'decision-rule'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'process-event'}), (t:KGClass {id:'process-task'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'process-event'}), (t:KGClass {id:'process-gateway'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'process-task'}), (t:KGClass {id:'process-task'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'process-task'}), (t:KGClass {id:'process-gateway'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'process-task'}), (t:KGClass {id:'process-event'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'process-gateway'}), (t:KGClass {id:'process-task'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'process-gateway'}), (t:KGClass {id:'process-gateway'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'process-gateway'}), (t:KGClass {id:'process-event'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'process-task'}), (t:KGClass {id:'process-task'}) MERGE (s)-[:MESSAGETO {predicate:'messageTo'}]->(t);
MATCH (s:KGClass {id:'process-task'}), (t:KGClass {id:'process-event'}) MERGE (s)-[:MESSAGETO {predicate:'messageTo'}]->(t);
MATCH (s:KGClass {id:'process-event'}), (t:KGClass {id:'process-task'}) MERGE (s)-[:MESSAGETO {predicate:'messageTo'}]->(t);
MATCH (s:KGClass {id:'process-participant'}), (t:KGClass {id:'persona'}) MERGE (s)-[:PERFORMEDBY {predicate:'performedBy'}]->(t);
MATCH (s:KGClass {id:'decision-table'}), (t:KGClass {id:'process-task'}) MERGE (s)-[:INVOKEDBY {predicate:'invokedBy'}]->(t);
MATCH (s:KGClass {id:'decision-table'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:INVOKEDBY {predicate:'invokedBy'}]->(t);
MATCH (s:KGClass {id:'input-clause'}), (t:KGClass {id:'data-element'}) MERGE (s)-[:READS {predicate:'reads'}]->(t);
MATCH (s:KGClass {id:'decision-rule'}), (t:KGClass {id:'citation'}) MERGE (s)-[:CITESSOURCE {predicate:'citesSource'}]->(t);
MATCH (s:KGClass {id:'data-element'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:DEFINEDBY {predicate:'definedBy'}]->(t);
MATCH (s:KGClass {id:'data-element'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'persona'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);

// Verification. Must return 3 rows -- one per imported class this layer
// builds on. Fewer means an imported layer was not loaded and edges above are missing.
// MATCH (c:KGClass) WHERE c.id IN ['citation', 'external-artifact', 'terminology-code'] RETURN c.id;
