#!/usr/bin/env node
// Builds ontology/<layer>.cypher and ontology/<layer>.ttl from an ontology JSON file.
//
// Both are views of the same model, committed rather than generated on demand because the point of
// a standalone ontology repository is that someone can fetch it in the format their tool reads --
// Turtle into Protege, Cypher into Neo4j -- without installing a toolchain first. `--check` keeps
// them from drifting from ontology.json.
//
// These carry the TYPE graph: classes and licensed edges. They are not DAK data. See docs/STORAGE.md.
//
//   node tools/build-exports.mjs
//   node tools/build-exports.mjs --check

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
// Which ontology files to export. Each is authored or generated elsewhere; this only projects.
const LAYERS = ["l1"];

const camel = (name) =>
  name.split(/[^A-Za-z0-9]+/).filter(Boolean)
    .map((w) => (/^[A-Z0-9]+$/.test(w) ? w : w[0].toUpperCase() + w.slice(1)))
    .join("");

const cy = (s) => String(s).replace(/\\/g, "\\\\").replace(/'/g, "\\'");
const tt = (s) => String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');

export function buildCypher(ont) {
  const L = [
    `// WHO SMART Guidelines knowledge graph -- ${(ont.layer ?? "").toUpperCase()} ONTOLOGY (type graph).`,
    "// Generated by tools/build-exports.mjs. Do not edit; edit the ontology JSON.",
    "//",
    "// These are CLASSES and LICENSED EDGES, not DAK instance data. Loading this gives you the",
    "// schema to explore; a DAK's own graph is generated by that DAK's IG build. See docs/STORAGE.md.",
    "//",
    "// Every statement is MERGE, so re-running is safe.",
    "",
    "CREATE CONSTRAINT kgclass_id IF NOT EXISTS",
    "FOR (c:KGClass) REQUIRE c.id IS UNIQUE;",
    "",
  ];
  for (const c of ont.classes) {
    L.push(
      `MERGE (:KGClass:${c.kind} {id:'${cy(c.id)}', name:'${cy(c.name)}', ` +
      `kind:'${c.kind}', iri:'${c.iri}'` +
      (c.archimateType ? `, archimateType:'${c.archimateType}'` : "") + `});`);
  }
  L.push("");
  for (const e of ont.edges) {
    const props = [`predicate:'${e.predicate}'`];
    if (e.qualifier) props.push(`qualifier:'${cy(e.qualifier)}'`);
    if (e.access) props.push(`access:'${e.access}'`);
    if (e.archimateType) props.push(`archimateType:'${e.archimateType}'`);
    L.push(
      `MATCH (s:KGClass {id:'${e.source}'}), (t:KGClass {id:'${e.target}'}) ` +
      `MERGE (s)-[:${e.predicate.toUpperCase()} {${props.join(", ")}}]->(t);`);
  }
  return L.join("\n") + "\n";
}

export function buildContext(ont) {
  const camelId = (id) => id.split("-").map((w, i) => (i ? w[0].toUpperCase() + w.slice(1) : w)).join("");
  const aliases = {};
  for (const c of ont.classes) aliases[camel(c.name)] = `sgkg:${c.id}`;
  const predicates = {};
  for (const p of ont.predicates) predicates[p.predicate] = { "@id": `sgkg:${p.predicate}` };
  return {
    "@context": {
      "@version": 1.1,
      rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
      rdfs: "http://www.w3.org/2000/01/rdf-schema#",
      owl: "http://www.w3.org/2002/07/owl#",
      skos: "http://www.w3.org/2004/02/skos/core#",
      dcterms: "http://purl.org/dc/terms/",
      prov: "http://www.w3.org/ns/prov#",
      xsd: "http://www.w3.org/2001/XMLSchema#",
      sgkg: ont.namespace,
      id: "@id",
      type: "@type",
      label: { "@id": "rdfs:label" },
      properties: { "@id": "sgkg:properties", "@container": "@index" },
      nodes: { "@id": "sgkg:node", "@container": "@set" },
      edges: { "@id": "sgkg:edge", "@container": "@set" },
      Statement: "rdf:Statement",
      Entity: "prov:Entity",
      predicate: { "@id": "rdf:predicate", "@type": "@vocab" },
      source: { "@id": "rdf:subject", "@type": "@id" },
      target: { "@id": "rdf:object", "@type": "@id" },
      qualifier: { "@id": "sgkg:qualifier" },
      derivation: { "@id": "sgkg:derivation" },
      evidence: { "@id": "sgkg:evidence" },
      location: { "@id": "sgkg:location" },
      quote: { "@id": "sgkg:quote" },
      note: { "@id": "skos:note" },
      skill: { "@id": "sgkg:skill" },
      generatedAt: { "@id": "prov:generatedAtTime", "@type": "xsd:dateTime" },
      wasDerivedFrom: { "@id": "prov:wasDerivedFrom", "@type": "@id" },
      ontologyVersion: { "@id": "sgkg:ontologyVersion" },
      ...predicates,
      ...aliases,
    },
  };
}

export function buildTurtle(ont) {
  const NS = ont.namespace;
  const byId = new Map(ont.classes.map((c) => [c.id, c]));
  const T = [
    `@prefix sgkg: <${NS}> .`,
    "@prefix owl:  <http://www.w3.org/2002/07/owl#> .",
    "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
    "@prefix skos: <http://www.w3.org/2004/02/skos/core#> .",
    "",
    `<${NS.replace(/\/$/, "")}> a owl:Ontology ;`,
    `  rdfs:label "WHO SMART Guidelines ${(ont.layer ?? "").toUpperCase()} ontology" ;`,
    `  rdfs:comment "${tt(ont.note ?? "")} Pairwise licensing is carried as sub-properties, ` +
      `because a relationship is licensed between specific class pairs while an OWL object ` +
      `property has one global domain and range." .`,
    "",
    "### Node kinds", "",
  ];

  const KIND_NOTES = {
    Concept: "A thing the guidance is about.",
    Source: "A published document, or a part of one, that guidance is stated in.",
    Reference: "A pointer out of this graph. Carries identity only; asserts nothing about the target.",
    Artifact: "A file that carries a concept.",
    AuthoringProcess: "A step that produces an artifact.",
    Repository: "A store an artifact is drawn from.",
  };
  for (const kind of [...new Set(ont.classes.map((c) => c.kind))].sort()) {
    T.push(`sgkg:${kind} a owl:Class ; rdfs:label "${tt(kind)}" ; ` +
           `rdfs:comment "${tt(KIND_NOTES[kind] ?? kind)}" .`);
  }
  T.push("", "### Classes", "");

  for (const c of ont.classes) {
    T.push(`sgkg:${camel(c.name)} a owl:Class ;`);
    T.push(`  rdfs:subClassOf sgkg:${c.kind} ;`);
    T.push(`  rdfs:label "${tt(c.name)}" ;`);
    T.push(`  skos:notation "${c.id}" ;`);
    T.push(`  rdfs:comment "${tt(c.note ?? `${c.archimateType ?? ""} ${c.archimateId ?? ""}`.trim())}" .`);
    T.push("");
  }

  T.push("### Object properties (the ArchiMate relationship vocabulary)", "");
  const used = new Set(ont.edges.map((e) => e.predicate));
  for (const p of ont.predicates) {
    T.push(`sgkg:${p.predicate} a owl:ObjectProperty ;`);
    T.push(`  rdfs:label "${p.predicate}" ;`);
    T.push(`  rdfs:comment "${tt(p.note ?? p.archimateType ?? "")}` +
           `${used.has(p.predicate) ? "" : " -- declared but unused by the current model"}" .`);
    T.push("");
  }

  T.push(
    "### Licensed edges, as qualified sub-properties",
    "# One per (source class, predicate, target class) triple the ArchiMate model licenses.",
    "# Domain and range on the sub-property is what preserves pairwise licensing: a single global",
    "# domain/range on sgkg:associatedWith would be a union of everything and would permit",
    "# Business Process aggregates Data Element, which the model does not.",
    "");

  const seen = new Map();
  for (const e of ont.edges) {
    const s = byId.get(e.source);
    const t = byId.get(e.target);
    const base = `${e.predicate}_${camel(s.name)}_${camel(t.name)}`;
    const n = seen.get(base) ?? 0;
    seen.set(base, n + 1);
    const name = n === 0 ? base : `${base}_${n + 1}`;
    T.push(`sgkg:${name} a owl:ObjectProperty ;`);
    T.push(`  rdfs:subPropertyOf sgkg:${e.predicate} ;`);
    T.push(`  rdfs:domain sgkg:${camel(s.name)} ;`);
    T.push(`  rdfs:range sgkg:${camel(t.name)} ;`);
    if (e.qualifier) T.push(`  skos:note "qualifier: ${tt(e.qualifier)}" ;`);
    if (e.access) T.push(`  skos:note "access: ${e.access}" ;`);
    T.push(`  rdfs:label "${tt(s.name)} ${tt(e.qualifier ?? e.predicate)} ${tt(t.name)}" .`);
    T.push("");
  }
  return T.join("\n") + "\n";
}

function main() {
  const check = process.argv.includes("--check");
  let total = 0;

  for (const layer of LAYERS) {
    const src = join(ROOT, "ontology", `${layer}.json`);
    if (!existsSync(src)) {
      console.error(`ontology/${layer}.json is missing.`);
      process.exit(1);
    }
    const ont = JSON.parse(readFileSync(src, "utf8"));
    const outputs = [
      [join(ROOT, "ontology", `${layer}.cypher`), buildCypher(ont)],
      [join(ROOT, "ontology", `${layer}.ttl`), buildTurtle(ont)],
      [join(ROOT, "ontology", `${layer}.context.jsonld`), JSON.stringify(buildContext(ont), null, 2) + "\n"],
    ];

    if (check) {
      for (const [file, want] of outputs) {
        const name = relative(ROOT, file);
        if (!existsSync(file)) {
          console.error(`${name} is missing. Run: node tools/build-exports.mjs`);
          process.exit(1);
        }
        if (readFileSync(file, "utf8") !== want) {
          console.error(`${name} is stale. Run: node tools/build-exports.mjs`);
          process.exit(1);
        }
      }
      console.log(`${layer}: exports current -- ${ont.classes.length} classes, ${ont.edges.length} edges`);
    } else {
      for (const [file, text] of outputs) writeFileSync(file, text, "utf8");
      console.log(`${layer}: wrote ${layer}.cypher, ${layer}.ttl, ${layer}.context.jsonld -- ` +
                  `${ont.classes.length} classes, ${ont.edges.length} edges`);
    }
    total += ont.edges.length;
  }
  if (!total) { console.error("no edges exported"); process.exit(1); }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
